[package]
name = "twitter"
version = "1.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
reqwest = { version = "0.12.23", default-features = false, features = ['json', 'multipart', 'stream', 'rustls-tls'] }
serde =  "1.0.219"
serde_json = "1.0.143"
oauth = { version = "0.6", package = "oauth1-request" }
dirs = "6.0.0"
toml = "0.9.5"
clap = { version = "4.5.46", features = ["derive"] }
infer = "0.19.0"
futures-util = "0.3.31"
indicatif = "0.18.0"
tokio = { version = "1.48.0", features = ['macros', 'rt-multi-thread'] } 

[profile.release]
opt-level = "z" 
lto = true  
codegen-units = 1
panic = "abort"
strip = true 
